0 0 dataAuditErrors
1268 0 PWBLK_StampErrorFloat
1269 0 PWBLK_StampErrorMult
1270 0 PWBLK_StampErrorConnect
1276 0 PSUB_StampErrorFloat
1277 0 PSUB_StampErrorMult
1278 0 PSUB_StampErrorConnect
1283 0 wel_StampErrorFloat
1284 0 wel_StampErrorMult
1285 0 wel_StampErrorConnect
1290 0 TWEL_StampErrorFloat
1291 0 TWEL_StampErrorMult
1292 0 TWEL_StampErrorConnect
1298 0 PSUB_P_StampErrorFloat
1299 0 PSUB_P_StampErrorMult
1300 0 PSUB_P_StampErrorConnect
1305 0 B_DNW_StampErrorFloat
1306 0 B_DNW_StampErrorMult
1307 0 B_DNW_StampErrorConnect
1311 0  nsd/ptap butting issue: nsd/ptap need to be connected by metal and contact
1312 0  psd/ntap butting issue: psd/ntap need to be connected by metal and contact
1317 0 ptap is wrongly connected to POWER ! 
1323 0 ntap is wrongly connected to GROUND ! 
4634 0 malformed device NG_HS
4635 0 malformed device PG_HS
4636 0 malformed device MNGATE_C
4637 0 malformed device MPGATE_C
4638 0 malformed device NTGATE
4639 0 malformed device PTGATE
4640 0 malformed device NSGATE
4641 0 malformed device TGNSGATE
4642 0 malformed device NLGATE
4643 0 malformed device PLGATE
4644 0 malformed device NHLGATE
4645 0 malformed device PHLGATE
4646 0 malformed device NLGAT
4647 0 malformed device NHLGAT
4648 0 malformed device NLTWGATE
4649 0 malformed device NLTGTWGATE
4650 0 malformed device NG_SP
4651 0 malformed device PG_SP
4652 0 malformed device NG_LL
4653 0 malformed device PG_LL
4654 0 malformed device welres
4655 0 malformed device snyres_mm
4656 0 malformed device spyres_mm
4657 0 malformed device snpyr_mm
4658 0 malformed device sppyr_mm
4659 0 malformed device nshrpyr_wel
4660 0 malformed device nshrpyr_psub
4661 0 malformed device nsndres_mm
4662 0 malformed device nsppyr_wel
4663 0 malformed device nsppyr_psub
4664 0 malformed device dndiod_mm
4665 0 malformed device dpdiod_mm
4666 0 malformed device dnwdiod_mm
4667 0 malformed device CMMC
4668 0 malformed device bjt_v5_mm
4669 0 malformed device bjt_v10_mm
4670 0 malformed device bjt_v15_mm
4671 0 malformed device MNGATE_RF
4672 0 malformed device MPGATE_RF
4673 0 malformed device NTGATE_RF
4674 0 malformed device PTGATE_RF
4675 0 malformed device NSGATE_RF
4676 0 malformed device TGNSGATE_RF
4677 0 malformed device nshrpyr_rf
4678 0 malformed device nsppyr_rf
4679 0 malformed device nsnpyr_rf
4680 0 malformed device npn5x5_s_rf
4681 0 malformed device npn2_s_rf
4682 0 malformed device npn5x5_n_rf
4683 0 malformed device npn2_n_rf
4684 0 malformed device pnp5x5_n_rf
4685 0 malformed device pnp2_n_rf
4686 0 malformed device nsdtw_rf
4687 0 malformed device dpesd_rf
4688 0 malformed device varmis_rf12
4689 0 malformed device varmis_rf33
4690 0 malformed device vard_rf
4691 0 malformed device CMMC_RF
4693 0 malformed device MOMVP1_MM
4694 0 malformed device MOMVP1_RF
4696 0 malformed device MOMVP2_MM
4697 0 malformed device MOMVP2_RF
4698 0 malformed device MOM_MESH_SY_WEL
4699 0 malformed device MOM_MESH_SY_PSUB
4700 0 malformed device MOM_MESH_ASY_WEL
4701 0 malformed device MOM_MESH_ASY_PSUB
4702 0 malformed device p_rf_pad
4703 0 malformed device N_IND_CR_0
4704 0 malformed device N_IND_CR
4705 0 malformed device N_IND_CR_P
4706 0 malformed device N_IND_SY
4707 0 malformed device N_IND_SY_P
4708 0 malformed device N_IND_SYC
4709 0 malformed device N_IND_SYC_P
4710 0 malformed device N_IND_SQ_0
4711 0 malformed device N_IND_SQ
4712 0 malformed device N_IND_SQ_P
4713 0 malformed device MOM_ARRAY_VP3_RFVCL_1
4714 0 malformed device MOM_ARRAY_VP3_RFVCL_2
4715 0 malformed device MOM_ARRAY_VP3_RFVCL_3
4716 0 malformed device MOM_ARRAY_VP3_RFVCL_4
4717 0 malformed device MOM_ARRAY_VP4_RFVCL_1
4718 0 malformed device MOM_ARRAY_VP4_RFVCL_2
4719 0 malformed device MOM_ARRAY_VP4_RFVCL_3
4720 0 malformed device MOM_ARRAY_VP4_RFVCL_4
5365 0 unstable device for MOM_ARRAY_VP4_RFVCL_4_Device_87
5366 0 unpreserved device MOM_ARRAY_VP4_RFVCL_4_Device_87
5367 0 unstable device for MOM_ARRAY_VP4_RFVCL_3_Device_86
5368 0 unpreserved device MOM_ARRAY_VP4_RFVCL_3_Device_86
5369 0 unstable device for MOM_ARRAY_VP4_RFVCL_2_Device_85
5370 0 unpreserved device MOM_ARRAY_VP4_RFVCL_2_Device_85
5371 0 unstable device for MOM_ARRAY_VP4_RFVCL_1_Device_84
5372 0 unpreserved device MOM_ARRAY_VP4_RFVCL_1_Device_84
5373 0 unstable device for MOM_ARRAY_VP3_RFVCL_4_Device_83
5374 0 unpreserved device MOM_ARRAY_VP3_RFVCL_4_Device_83
5375 0 unstable device for MOM_ARRAY_VP3_RFVCL_3_Device_82
5376 0 unpreserved device MOM_ARRAY_VP3_RFVCL_3_Device_82
5377 0 unstable device for MOM_ARRAY_VP3_RFVCL_2_Device_81
5378 0 unpreserved device MOM_ARRAY_VP3_RFVCL_2_Device_81
5379 0 unstable device for MOM_ARRAY_VP3_RFVCL_1_Device_80
5380 0 unpreserved device MOM_ARRAY_VP3_RFVCL_1_Device_80
5381 0 unstable device for N_IND_SQ_P_Device_79
5382 0 unpreserved device N_IND_SQ_P_Device_79
5383 0 unstable device for N_IND_SQ_Device_78
5384 0 unpreserved device N_IND_SQ_Device_78
5385 0 unstable device for N_IND_SQ_0_Device_77
5386 0 unpreserved device N_IND_SQ_0_Device_77
5387 0 unstable device for N_IND_SYC_P_Device_76
5388 0 unpreserved device N_IND_SYC_P_Device_76
5389 0 unstable device for N_IND_SYC_Device_75
5390 0 unpreserved device N_IND_SYC_Device_75
5391 0 unstable device for N_IND_SY_P_Device_74
5392 0 unpreserved device N_IND_SY_P_Device_74
5393 0 unstable device for N_IND_SY_Device_73
5394 0 unpreserved device N_IND_SY_Device_73
5395 0 unstable device for N_IND_CR_P_Device_72
5396 0 unpreserved device N_IND_CR_P_Device_72
5397 0 unstable device for N_IND_CR_Device_71
5398 0 unpreserved device N_IND_CR_Device_71
5399 0 unstable device for N_IND_CR_0_Device_70
5400 0 unpreserved device N_IND_CR_0_Device_70
5401 0 unstable device for p_rf_pad_Device_69
5402 0 unpreserved device p_rf_pad_Device_69
5403 0 unstable device for MOM_MESH_ASY_PSUB_Device_68
5404 0 unpreserved device MOM_MESH_ASY_PSUB_Device_68
5405 0 unstable device for MOM_MESH_ASY_WEL_Device_67
5406 0 unpreserved device MOM_MESH_ASY_WEL_Device_67
5407 0 unstable device for MOM_MESH_SY_PSUB_Device_66
5408 0 unpreserved device MOM_MESH_SY_PSUB_Device_66
5409 0 unstable device for MOM_MESH_SY_WEL_Device_65
5410 0 unpreserved device MOM_MESH_SY_WEL_Device_65
5411 0 unstable device for MOMVP2_RF_Device_64
5412 0 unpreserved device MOMVP2_RF_Device_64
5413 0 unstable device for MOMVP2_MM_Device_62
5414 0 unpreserved device MOMVP2_MM_Device_62
5415 0 unstable device for MOMVP2_MM_Device_63
5416 0 unpreserved device MOMVP2_MM_Device_63
5417 0 unstable device for MOMVP1_RF_Device_61
5418 0 unpreserved device MOMVP1_RF_Device_61
5419 0 unstable device for MOMVP1_MM_Device_59
5420 0 unpreserved device MOMVP1_MM_Device_59
5421 0 unstable device for MOMVP1_MM_Device_60
5422 0 unpreserved device MOMVP1_MM_Device_60
5423 0 unstable device for CMMC_RF_Device_58
5424 0 unpreserved device CMMC_RF_Device_58
5425 0 unstable device for vard_rf_Device_57
5426 0 unpreserved device vard_rf_Device_57
5427 0 unstable device for varmis_rf33_Device_56
5428 0 unpreserved device varmis_rf33_Device_56
5429 0 unstable device for varmis_rf12_Device_55
5430 0 unpreserved device varmis_rf12_Device_55
5431 0 unstable device for dpesd_rf_Device_54
5432 0 unpreserved device dpesd_rf_Device_54
5433 0 unstable device for nsdtw_rf_Device_53
5434 0 unpreserved device nsdtw_rf_Device_53
5435 0 unstable device for pnp2_n_rf_Device_52
5436 0 unpreserved device pnp2_n_rf_Device_52
5437 0 unstable device for pnp5x5_n_rf_Device_51
5438 0 unpreserved device pnp5x5_n_rf_Device_51
5439 0 unstable device for npn2_n_rf_Device_50
5440 0 unpreserved device npn2_n_rf_Device_50
5441 0 unstable device for npn5x5_n_rf_Device_49
5442 0 unpreserved device npn5x5_n_rf_Device_49
5443 0 unstable device for npn2_s_rf_Device_48
5444 0 unpreserved device npn2_s_rf_Device_48
5445 0 unstable device for npn5x5_s_rf_Device_47
5446 0 unpreserved device npn5x5_s_rf_Device_47
5447 0 unstable device for nsnpyr_rf_Device_46
5448 0 unpreserved device nsnpyr_rf_Device_46
5449 0 unstable device for nsppyr_rf_Device_45
5450 0 unpreserved device nsppyr_rf_Device_45
5451 0 unstable device for nshrpyr_rf_Device_44
5452 0 unpreserved device nshrpyr_rf_Device_44
5453 0 unstable device for TGNSGATE_RF_Device_43
5454 0 unpreserved device TGNSGATE_RF_Device_43
5455 0 unstable device for NSGATE_RF_Device_42
5456 0 unpreserved device NSGATE_RF_Device_42
5457 0 unstable device for PTGATE_RF_Device_41
5458 0 unpreserved device PTGATE_RF_Device_41
5459 0 unstable device for NTGATE_RF_Device_40
5460 0 unpreserved device NTGATE_RF_Device_40
5461 0 unstable device for MPGATE_RF_Device_39
5462 0 unpreserved device MPGATE_RF_Device_39
5463 0 unstable device for MNGATE_RF_Device_38
5464 0 unpreserved device MNGATE_RF_Device_38
5465 0 unstable device for bjt_v15_mm_BJT_37
5466 0 unpreserved device bjt_v15_mm_BJT_37
5467 0 unstable device for bjt_v10_mm_BJT_36
5468 0 unpreserved device bjt_v10_mm_BJT_36
5469 0 unstable device for bjt_v5_mm_BJT_35
5470 0 unpreserved device bjt_v5_mm_BJT_35
5471 0 unstable device for CMMC_Device_34
5472 0 unpreserved device CMMC_Device_34
5473 0 unstable device for dnwdiod_mm_DIODE_33
5474 0 unpreserved device dnwdiod_mm_DIODE_33
5475 0 unstable device for dpdiod_mm_DIODE_32
5476 0 unpreserved device dpdiod_mm_DIODE_32
5477 0 unstable device for dndiod_mm_DIODE_31
5478 0 unpreserved device dndiod_mm_DIODE_31
5479 0 unstable device for nsppyr_psub_Device_30
5480 0 unpreserved device nsppyr_psub_Device_30
5481 0 unstable device for nsppyr_wel_Device_29
5482 0 unpreserved device nsppyr_wel_Device_29
5483 0 unstable device for nsndres_mm_Device_28
5484 0 unpreserved device nsndres_mm_Device_28
5485 0 unstable device for nshrpyr_psub_Device_27
5486 0 unpreserved device nshrpyr_psub_Device_27
5487 0 unstable device for nshrpyr_wel_Device_26
5488 0 unpreserved device nshrpyr_wel_Device_26
5489 0 unstable device for sppyr_mm_Device_25
5490 0 unpreserved device sppyr_mm_Device_25
5491 0 unstable device for snpyr_mm_Device_24
5492 0 unpreserved device snpyr_mm_Device_24
5493 0 unstable device for spyres_mm_Device_23
5494 0 unpreserved device spyres_mm_Device_23
5495 0 unstable device for snyres_mm_Device_22
5496 0 unpreserved device snyres_mm_Device_22
5497 0 unstable device for welres_RES_21
5498 0 unpreserved device welres_RES_21
5499 0 unstable device for PG_LL_MOS_20
5500 0 unpreserved device PG_LL_MOS_20
5501 0 unstable device for NG_LL_MOS_19
5502 0 unpreserved device NG_LL_MOS_19
5503 0 unstable device for PG_SP_MOS_18
5504 0 unpreserved device PG_SP_MOS_18
5505 0 unstable device for NG_SP_MOS_17
5506 0 unpreserved device NG_SP_MOS_17
5507 0 unstable device for NLTGTWGATE_MOS_16
5508 0 unpreserved device NLTGTWGATE_MOS_16
5509 0 unstable device for NLTWGATE_MOS_15
5510 0 unpreserved device NLTWGATE_MOS_15
5511 0 unstable device for NHLGAT_MOS_14
5512 0 unpreserved device NHLGAT_MOS_14
5513 0 unstable device for NLGAT_MOS_13
5514 0 unpreserved device NLGAT_MOS_13
5515 0 unstable device for PHLGATE_MOS_12
5516 0 unpreserved device PHLGATE_MOS_12
5517 0 unstable device for NHLGATE_MOS_11
5518 0 unpreserved device NHLGATE_MOS_11
5519 0 unstable device for PLGATE_MOS_10
5520 0 unpreserved device PLGATE_MOS_10
5521 0 unstable device for NLGATE_MOS_9
5522 0 unpreserved device NLGATE_MOS_9
5523 0 unstable device for TGNSGATE_MOS_8
5524 0 unpreserved device TGNSGATE_MOS_8
5525 0 unstable device for NSGATE_MOS_7
5526 0 unpreserved device NSGATE_MOS_7
5527 0 unstable device for PTGATE_MOS_6
5528 0 unpreserved device PTGATE_MOS_6
5529 0 unstable device for NTGATE_MOS_5
5530 0 unpreserved device NTGATE_MOS_5
5531 0 unstable device for MPGATE_C_MOS_4
5532 0 unpreserved device MPGATE_C_MOS_4
5533 0 unstable device for MNGATE_C_MOS_3
5534 0 unpreserved device MNGATE_C_MOS_3
5535 0 unstable device for PG_HS_MOS_2
5536 0 unpreserved device PG_HS_MOS_2
5537 0 unstable device for NG_HS_MOS_1
5538 0 unpreserved device NG_HS_MOS_1
