0 0 dataAuditErrors
1337 0  nsd/ptap butting issue: nsd/ptap need to be connected by metal and contact
1338 0  psd/ntap butting issue: psd/ntap need to be connected by metal and contact
1343 0 ptap is wrongly connected to POWER ! 
1349 0 ntap is wrongly connected to GROUND ! 
4901 0 malformed device NG_HS
4902 0 malformed device PG_HS
4903 0 malformed device MNGATE_C
4904 0 malformed device MPGATE_C
4905 0 malformed device NTGATE
4906 0 malformed device PTGATE
4907 0 malformed device NSGATE
4908 0 malformed device TGNSGATE
4909 0 malformed device NLGATE
4910 0 malformed device PLGATE
4911 0 malformed device NHLGATE
4912 0 malformed device PHLGATE
4913 0 malformed device NLGAT
4914 0 malformed device NHLGAT
4915 0 malformed device NLTWGATE
4916 0 malformed device NLTGTWGATE
4917 0 malformed device NG_SP
4918 0 malformed device PG_SP
4919 0 malformed device NG_LL
4920 0 malformed device PG_LL
4921 0 malformed device RBNPG_LL_B6T228
4922 0 malformed device RBNPD_LL_B6T228
4923 0 malformed device RBPGAT_LL_B6T228
4924 0 malformed device RBNPG_LL_B8T466
4925 0 malformed device RBNPD_LL_B8T466
4926 0 malformed device RBPGAT_LL_B8T466
4927 0 malformed device welres
4928 0 malformed device RBNPG_HS_B6T228
4929 0 malformed device RBNPD_HS_B6T228
4930 0 malformed device RBPGAT_HS_B6T228
4931 0 malformed device RBNPG_HS_B8T466
4932 0 malformed device RBNPD_HS_B8T466
4933 0 malformed device RBPGAT_HS_B8T466
4934 0 malformed device snyres_mm
4935 0 malformed device spyres_mm
4936 0 malformed device snpyr_mm
4937 0 malformed device sppyr_mm
4938 0 malformed device nshrpyr_wel
4939 0 malformed device nshrpyr_psub
4940 0 malformed device nsndres_mm
4941 0 malformed device nsppyr_wel
4942 0 malformed device nsppyr_psub
4943 0 malformed device dndiod_mm
4944 0 malformed device dpdiod_mm
4945 0 malformed device dnwdiod_mm
4946 0 malformed device CMMC
4947 0 malformed device bjt_v5_mm
4948 0 malformed device bjt_v10_mm
4949 0 malformed device bjt_v15_mm
4950 0 malformed device MNGATE_RF
4951 0 malformed device MPGATE_RF
4952 0 malformed device NTGATE_RF
4953 0 malformed device PTGATE_RF
4954 0 malformed device NSGATE_RF
4955 0 malformed device TGNSGATE_RF
4956 0 malformed device nshrpyr_rf
4957 0 malformed device nsppyr_rf
4958 0 malformed device nsnpyr_rf
4959 0 malformed device npn5x5_s_rf
4960 0 malformed device npn2_s_rf
4961 0 malformed device npn5x5_n_rf
4962 0 malformed device npn2_n_rf
4963 0 malformed device pnp5x5_n_rf
4964 0 malformed device pnp2_n_rf
4965 0 malformed device nsdtw_rf
4966 0 malformed device dpesd_rf
4967 0 malformed device varmis_rf12
4968 0 malformed device varmis_rf33
4969 0 malformed device vard_rf
4970 0 malformed device CMMC_RF
4972 0 malformed device MOMVP1_MM
4973 0 malformed device MOMVP1_RF
4975 0 malformed device MOMVP2_MM
4976 0 malformed device MOMVP2_RF
4977 0 malformed device MOM_MESH_SY_WEL
4978 0 malformed device MOM_MESH_SY_PSUB
4979 0 malformed device MOM_MESH_ASY_WEL
4980 0 malformed device MOM_MESH_ASY_PSUB
4981 0 malformed device p_rf_pad
4982 0 malformed device N_IND_CR_0
4983 0 malformed device N_IND_CR
4984 0 malformed device N_IND_CR_P
4985 0 malformed device N_IND_SY
4986 0 malformed device N_IND_SY_P
4987 0 malformed device N_IND_SYC
4988 0 malformed device N_IND_SYC_P
4989 0 malformed device N_IND_SQ_0
4990 0 malformed device N_IND_SQ
4991 0 malformed device N_IND_SQ_P
4992 0 malformed device MOM_ARRAY_VP3_RFVCL_1
4993 0 malformed device MOM_ARRAY_VP3_RFVCL_2
4994 0 malformed device MOM_ARRAY_VP3_RFVCL_3
4995 0 malformed device MOM_ARRAY_VP3_RFVCL_4
4996 0 malformed device MOM_ARRAY_VP4_RFVCL_1
4997 0 malformed device MOM_ARRAY_VP4_RFVCL_2
4998 0 malformed device MOM_ARRAY_VP4_RFVCL_3
4999 0 malformed device MOM_ARRAY_VP4_RFVCL_4
5710 0 unstable device for MOM_ARRAY_VP4_RFVCL_4_Device_99
5711 0 unpreserved device MOM_ARRAY_VP4_RFVCL_4_Device_99
5712 0 unstable device for MOM_ARRAY_VP4_RFVCL_3_Device_98
5713 0 unpreserved device MOM_ARRAY_VP4_RFVCL_3_Device_98
5714 0 unstable device for MOM_ARRAY_VP4_RFVCL_2_Device_97
5715 0 unpreserved device MOM_ARRAY_VP4_RFVCL_2_Device_97
5716 0 unstable device for MOM_ARRAY_VP4_RFVCL_1_Device_96
5717 0 unpreserved device MOM_ARRAY_VP4_RFVCL_1_Device_96
5718 0 unstable device for MOM_ARRAY_VP3_RFVCL_4_Device_95
5719 0 unpreserved device MOM_ARRAY_VP3_RFVCL_4_Device_95
5720 0 unstable device for MOM_ARRAY_VP3_RFVCL_3_Device_94
5721 0 unpreserved device MOM_ARRAY_VP3_RFVCL_3_Device_94
5722 0 unstable device for MOM_ARRAY_VP3_RFVCL_2_Device_93
5723 0 unpreserved device MOM_ARRAY_VP3_RFVCL_2_Device_93
5724 0 unstable device for MOM_ARRAY_VP3_RFVCL_1_Device_92
5725 0 unpreserved device MOM_ARRAY_VP3_RFVCL_1_Device_92
5726 0 unstable device for N_IND_SQ_P_Device_91
5727 0 unpreserved device N_IND_SQ_P_Device_91
5728 0 unstable device for N_IND_SQ_Device_90
5729 0 unpreserved device N_IND_SQ_Device_90
5730 0 unstable device for N_IND_SQ_0_Device_89
5731 0 unpreserved device N_IND_SQ_0_Device_89
5732 0 unstable device for N_IND_SYC_P_Device_88
5733 0 unpreserved device N_IND_SYC_P_Device_88
5734 0 unstable device for N_IND_SYC_Device_87
5735 0 unpreserved device N_IND_SYC_Device_87
5736 0 unstable device for N_IND_SY_P_Device_86
5737 0 unpreserved device N_IND_SY_P_Device_86
5738 0 unstable device for N_IND_SY_Device_85
5739 0 unpreserved device N_IND_SY_Device_85
5740 0 unstable device for N_IND_CR_P_Device_84
5741 0 unpreserved device N_IND_CR_P_Device_84
5742 0 unstable device for N_IND_CR_Device_83
5743 0 unpreserved device N_IND_CR_Device_83
5744 0 unstable device for N_IND_CR_0_Device_82
5745 0 unpreserved device N_IND_CR_0_Device_82
5746 0 unstable device for p_rf_pad_Device_81
5747 0 unpreserved device p_rf_pad_Device_81
5748 0 unstable device for MOM_MESH_ASY_PSUB_Device_80
5749 0 unpreserved device MOM_MESH_ASY_PSUB_Device_80
5750 0 unstable device for MOM_MESH_ASY_WEL_Device_79
5751 0 unpreserved device MOM_MESH_ASY_WEL_Device_79
5752 0 unstable device for MOM_MESH_SY_PSUB_Device_78
5753 0 unpreserved device MOM_MESH_SY_PSUB_Device_78
5754 0 unstable device for MOM_MESH_SY_WEL_Device_77
5755 0 unpreserved device MOM_MESH_SY_WEL_Device_77
5756 0 unstable device for MOMVP2_RF_Device_76
5757 0 unpreserved device MOMVP2_RF_Device_76
5758 0 unstable device for MOMVP2_MM_Device_74
5759 0 unpreserved device MOMVP2_MM_Device_74
5760 0 unstable device for MOMVP2_MM_Device_75
5761 0 unpreserved device MOMVP2_MM_Device_75
5762 0 unstable device for MOMVP1_RF_Device_73
5763 0 unpreserved device MOMVP1_RF_Device_73
5764 0 unstable device for MOMVP1_MM_Device_71
5765 0 unpreserved device MOMVP1_MM_Device_71
5766 0 unstable device for MOMVP1_MM_Device_72
5767 0 unpreserved device MOMVP1_MM_Device_72
5768 0 unstable device for CMMC_RF_Device_70
5769 0 unpreserved device CMMC_RF_Device_70
5770 0 unstable device for vard_rf_Device_69
5771 0 unpreserved device vard_rf_Device_69
5772 0 unstable device for varmis_rf33_Device_68
5773 0 unpreserved device varmis_rf33_Device_68
5774 0 unstable device for varmis_rf12_Device_67
5775 0 unpreserved device varmis_rf12_Device_67
5776 0 unstable device for dpesd_rf_Device_66
5777 0 unpreserved device dpesd_rf_Device_66
5778 0 unstable device for nsdtw_rf_Device_65
5779 0 unpreserved device nsdtw_rf_Device_65
5780 0 unstable device for pnp2_n_rf_Device_64
5781 0 unpreserved device pnp2_n_rf_Device_64
5782 0 unstable device for pnp5x5_n_rf_Device_63
5783 0 unpreserved device pnp5x5_n_rf_Device_63
5784 0 unstable device for npn2_n_rf_Device_62
5785 0 unpreserved device npn2_n_rf_Device_62
5786 0 unstable device for npn5x5_n_rf_Device_61
5787 0 unpreserved device npn5x5_n_rf_Device_61
5788 0 unstable device for npn2_s_rf_Device_60
5789 0 unpreserved device npn2_s_rf_Device_60
5790 0 unstable device for npn5x5_s_rf_Device_59
5791 0 unpreserved device npn5x5_s_rf_Device_59
5792 0 unstable device for nsnpyr_rf_Device_58
5793 0 unpreserved device nsnpyr_rf_Device_58
5794 0 unstable device for nsppyr_rf_Device_57
5795 0 unpreserved device nsppyr_rf_Device_57
5796 0 unstable device for nshrpyr_rf_Device_56
5797 0 unpreserved device nshrpyr_rf_Device_56
5798 0 unstable device for TGNSGATE_RF_Device_55
5799 0 unpreserved device TGNSGATE_RF_Device_55
5800 0 unstable device for NSGATE_RF_Device_54
5801 0 unpreserved device NSGATE_RF_Device_54
5802 0 unstable device for PTGATE_RF_Device_53
5803 0 unpreserved device PTGATE_RF_Device_53
5804 0 unstable device for NTGATE_RF_Device_52
5805 0 unpreserved device NTGATE_RF_Device_52
5806 0 unstable device for MPGATE_RF_Device_51
5807 0 unpreserved device MPGATE_RF_Device_51
5808 0 unstable device for MNGATE_RF_Device_50
5809 0 unpreserved device MNGATE_RF_Device_50
5810 0 unstable device for bjt_v15_mm_BJT_49
5811 0 unpreserved device bjt_v15_mm_BJT_49
5812 0 unstable device for bjt_v10_mm_BJT_48
5813 0 unpreserved device bjt_v10_mm_BJT_48
5814 0 unstable device for bjt_v5_mm_BJT_47
5815 0 unpreserved device bjt_v5_mm_BJT_47
5816 0 unstable device for CMMC_Device_46
5817 0 unpreserved device CMMC_Device_46
5818 0 unstable device for dnwdiod_mm_DIODE_45
5819 0 unpreserved device dnwdiod_mm_DIODE_45
5820 0 unstable device for dpdiod_mm_DIODE_44
5821 0 unpreserved device dpdiod_mm_DIODE_44
5822 0 unstable device for dndiod_mm_DIODE_43
5823 0 unpreserved device dndiod_mm_DIODE_43
5824 0 unstable device for nsppyr_psub_RES_42
5825 0 unpreserved device nsppyr_psub_RES_42
5826 0 unstable device for nsppyr_wel_RES_41
5827 0 unpreserved device nsppyr_wel_RES_41
5828 0 unstable device for nsndres_mm_RES_40
5829 0 unpreserved device nsndres_mm_RES_40
5830 0 unstable device for nshrpyr_psub_Device_39
5831 0 unpreserved device nshrpyr_psub_Device_39
5832 0 unstable device for nshrpyr_wel_Device_38
5833 0 unpreserved device nshrpyr_wel_Device_38
5834 0 unstable device for sppyr_mm_Device_37
5835 0 unpreserved device sppyr_mm_Device_37
5836 0 unstable device for snpyr_mm_Device_36
5837 0 unpreserved device snpyr_mm_Device_36
5838 0 unstable device for spyres_mm_Device_35
5839 0 unpreserved device spyres_mm_Device_35
5840 0 unstable device for snyres_mm_Device_34
5841 0 unpreserved device snyres_mm_Device_34
5842 0 unstable device for RBPGAT_HS_B8T466_MOS_33
5843 0 unpreserved device RBPGAT_HS_B8T466_MOS_33
5844 0 unstable device for RBNPD_HS_B8T466_MOS_32
5845 0 unpreserved device RBNPD_HS_B8T466_MOS_32
5846 0 unstable device for RBNPG_HS_B8T466_MOS_31
5847 0 unpreserved device RBNPG_HS_B8T466_MOS_31
5848 0 unstable device for RBPGAT_HS_B6T228_MOS_30
5849 0 unpreserved device RBPGAT_HS_B6T228_MOS_30
5850 0 unstable device for RBNPD_HS_B6T228_MOS_29
5851 0 unpreserved device RBNPD_HS_B6T228_MOS_29
5852 0 unstable device for RBNPG_HS_B6T228_MOS_28
5853 0 unpreserved device RBNPG_HS_B6T228_MOS_28
5854 0 unstable device for welres_RES_27
5855 0 unpreserved device welres_RES_27
5856 0 unstable device for RBPGAT_LL_B8T466_MOS_26
5857 0 unpreserved device RBPGAT_LL_B8T466_MOS_26
5858 0 unstable device for RBNPD_LL_B8T466_MOS_25
5859 0 unpreserved device RBNPD_LL_B8T466_MOS_25
5860 0 unstable device for RBNPG_LL_B8T466_MOS_24
5861 0 unpreserved device RBNPG_LL_B8T466_MOS_24
5862 0 unstable device for RBPGAT_LL_B6T228_MOS_23
5863 0 unpreserved device RBPGAT_LL_B6T228_MOS_23
5864 0 unstable device for RBNPD_LL_B6T228_MOS_22
5865 0 unpreserved device RBNPD_LL_B6T228_MOS_22
5866 0 unstable device for RBNPG_LL_B6T228_MOS_21
5867 0 unpreserved device RBNPG_LL_B6T228_MOS_21
5868 0 unstable device for PG_LL_MOS_20
5869 0 unpreserved device PG_LL_MOS_20
5870 0 unstable device for NG_LL_MOS_19
5871 0 unpreserved device NG_LL_MOS_19
5872 0 unstable device for PG_SP_MOS_18
5873 0 unpreserved device PG_SP_MOS_18
5874 0 unstable device for NG_SP_MOS_17
5875 0 unpreserved device NG_SP_MOS_17
5876 0 unstable device for NLTGTWGATE_MOS_16
5877 0 unpreserved device NLTGTWGATE_MOS_16
5878 0 unstable device for NLTWGATE_MOS_15
5879 0 unpreserved device NLTWGATE_MOS_15
5880 0 unstable device for NHLGAT_MOS_14
5881 0 unpreserved device NHLGAT_MOS_14
5882 0 unstable device for NLGAT_MOS_13
5883 0 unpreserved device NLGAT_MOS_13
5884 0 unstable device for PHLGATE_MOS_12
5885 0 unpreserved device PHLGATE_MOS_12
5886 0 unstable device for NHLGATE_MOS_11
5887 0 unpreserved device NHLGATE_MOS_11
5888 0 unstable device for PLGATE_MOS_10
5889 0 unpreserved device PLGATE_MOS_10
5890 0 unstable device for NLGATE_MOS_9
5891 0 unpreserved device NLGATE_MOS_9
5892 0 unstable device for TGNSGATE_MOS_8
5893 0 unpreserved device TGNSGATE_MOS_8
5894 0 unstable device for NSGATE_MOS_7
5895 0 unpreserved device NSGATE_MOS_7
5896 0 unstable device for PTGATE_MOS_6
5897 0 unpreserved device PTGATE_MOS_6
5898 0 unstable device for NTGATE_MOS_5
5899 0 unpreserved device NTGATE_MOS_5
5900 0 unstable device for MPGATE_C_MOS_4
5901 0 unpreserved device MPGATE_C_MOS_4
5902 0 unstable device for MNGATE_C_MOS_3
5903 0 unpreserved device MNGATE_C_MOS_3
5904 0 unstable device for PG_HS_MOS_2
5905 0 unpreserved device PG_HS_MOS_2
5906 0 unstable device for NG_HS_MOS_1
5907 0 unpreserved device NG_HS_MOS_1
